### ISSUE TITLE
[joss][docs] Developer docs

### ISSUE THREAD

**Issue by sneakers-the-rat** [neuroanatomy/thresholdmann#17]
Part of: https://github.com/openjournals/joss-reviews/issues/6336

Collecting ideas for developer docs here rather than in separate issues. Trying to minimize nags and only focus on things that I think would be helpful for inviting contributors and allowing for maintenance

- [ ] How to run tests? (looks pretty standard, `npm install && npm run test`)
- [ ] Expectations for contributions in `Contributing.md` - "test new functionality, run tests, etc."
- ... (will update as i continue to read)

**Comment by sneakers-the-rat** [comment]
Fabulous! That's pretty much all i came up with as i was reading! feel free to close

**Comment by katjaq** [comment]
Great :) Thank you.
