### ISSUE TITLE
[joss][ui] easier point moving

### ISSUE THREAD

**Issue by anibalsolon** [neuroanatomy/thresholdmann#37]
Part of: https://github.com/openjournals/joss-reviews/issues/6336

A suggestion: Unless it is a common user case to add points very closely, I believe dragging and dropping could always be enabled, thus removing the 'Move' mode.

![image](https://github.com/neuroanatomy/thresholdmann/assets/562525/097aaf20-f6c2-4f49-b22c-60225821ef5f)

**Comment by katjaq** [comment]
Thank you for the suggestion. We thought about it , but we prefer to keep these 4 options separated. Each of them requires just one key press to be active, out of only 4 options, which shouldn't be in the way of a fluid working process. 
The 4 options allow for a quick select of the control point to then change its value; if moving were enabled this could potentially lead to unexpected behaviour. It is also a nice use case to place control points close to each other to obtain boundaries – for example one to exclude the meninges; one to include the cortex.
