### ISSUE TITLE
[joss][feature] negative selection & flood fill

### ISSUE THREAD

**Issue by anibalsolon** [neuroanatomy/thresholdmann#40]
Part of: https://github.com/openjournals/joss-reviews/issues/6336

Have you folks crossed through the need of control points that remove such range of values?

In the same topic, have you considered using flood fill ("magic wand") to perform selection of some brain structures, while maintaining others intact?

**Comment by katjaq** [comment]
We hadn't thought about flood fill. It may be nice to have in some cases. We have thought, however, about adding some basic mathematical morphology tools (erosion, dilation, closing, opening, connected components, etc.). At the moment, we don't have an efficient implementation, and we do all that type of post-processing using scikit-image, in Python.
